---
# Source: local-static-provisioner/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vchord-nvme-provisioner
  namespace: default
  labels:
    helm.sh/chart: local-static-provisioner-2.0.0
    app.kubernetes.io/name: vchord-nvme-provisioner
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: release-name
---
# Source: local-static-provisioner/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: vchord-nvme-provisioner-config
  namespace: default
  labels:
    helm.sh/chart: local-static-provisioner-2.0.0
    app.kubernetes.io/name: vchord-nvme-provisioner
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: release-name
data:
  storageClassMap: |
    fast-disks:
      hostDir: /mnt/k8s-disks/
      mountDir: /mnt/k8s-disks/
      blockCleanerCommand:
        - "/scripts/shred.sh"
        - "2"
      volumeMode: Filesystem
      fsType: ext4
      namePattern: "*"
---
# Source: local-static-provisioner/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vchord-nvme-provisioner-node-clusterrole
  labels:
    helm.sh/chart: local-static-provisioner-2.0.0
    app.kubernetes.io/name: vchord-nvme-provisioner
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: release-name
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["watch"]
- apiGroups: ["", "events.k8s.io"]
  resources: ["events"]
  verbs: ["create", "update", "patch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
---
# Source: local-static-provisioner/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vchord-nvme-provisioner-node-binding
  labels:
    helm.sh/chart: local-static-provisioner-2.0.0
    app.kubernetes.io/name: vchord-nvme-provisioner
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: release-name
subjects:
- kind: ServiceAccount
  name: vchord-nvme-provisioner
  namespace: default
roleRef:
  kind: ClusterRole
  name: vchord-nvme-provisioner-node-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
# Source: local-static-provisioner/templates/daemonset_linux.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vchord-nvme-provisioner
  namespace: default
  labels:
    helm.sh/chart: local-static-provisioner-2.0.0
    app.kubernetes.io/name: vchord-nvme-provisioner
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: release-name
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vchord-nvme-provisioner
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vchord-nvme-provisioner
        app.kubernetes.io/instance: release-name
      annotations:
        checksum/config: 199be52e4b9f1fcf3bfbaa039adff107300e568462e54a30affe5384dbf5c1ba
    spec:
      hostPID: false
      serviceAccountName: vchord-nvme-provisioner
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: provisioner
          image: registry.k8s.io/sig-storage/local-volume-provisioner:v2.7.0
          securityContext:
            privileged: true
          env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JOB_CONTAINER_IMAGE
            value: registry.k8s.io/sig-storage/local-volume-provisioner:v2.7.0
          ports:
          - name: metrics
            containerPort: 8080
          volumeMounts:
            - name: provisioner-config
              mountPath: /etc/provisioner/config
              readOnly: true
            - name: provisioner-dev
              mountPath: /dev
            - name: fast-disks
              mountPath: /mnt/k8s-disks/
              mountPropagation: HostToContainer
      volumes:
        - name: provisioner-config
          configMap:
            name: vchord-nvme-provisioner-config
        - name: provisioner-dev
          hostPath:
            path: /dev
        - name: fast-disks
          hostPath:
            path: /mnt/k8s-disks/
---
# Only create this for K8s 1.9+
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-disks
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
# Supported policies: Delete, Retain
reclaimPolicy: Delete
