# test local ssd with node selector
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate-ssd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inflate-ssd
  template:
    metadata:
      labels:
        app:  inflate-ssd
    spec:
      nodeSelector:
        node.kubernetes.io/instance-type: i8g.xlarge
      terminationGracePeriodSeconds: 0
      containers:
      - name: "shell"
        image: "ubuntu:22.04"
        command: ["/bin/sh", "-c"]
        args: ["echo 'hello world' > /cache/test.txt && sleep 1 && cat /cache/test.txt && sleep 3600"]
        volumeMounts:
        - mountPath: /cache
          name: local-ssd-storage
      volumes:
      - name: local-ssd-storage
        persistentVolumeClaim:
          claimName: example-local-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: example-local-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 800Gi
  storageClassName: fast-disks
